### ISSUE TITLE
AssertionError: Could not resolve compression model checkpoint path: ./pretrained_models/encodec_4cb2048_giga.th

### ISSUE THREAD

**Issue by gjnave** [jasonppy/VoiceCraft#116]
I had this working on a previous install and now getting this. Any ideas?

Dora directory: /tmp/audiocraft_cognibuild
Traceback (most recent call last):
  File "/home/cognibuild/miniconda3/envs/voicecraft/lib/python3.9/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/cognibuild/miniconda3/envs/voicecraft/lib/python3.9/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cognibuild/miniconda3/envs/voicecraft/lib/python3.9/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/home/cognibuild/miniconda3/envs/voicecraft/lib/python3.9/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/cognibuild/miniconda3/envs/voicecraft/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/cognibuild/miniconda3/envs/voicecraft/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/home/cognibuild/miniconda3/envs/voicecraft/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/cognibuild/miniconda3/envs/voicecraft/lib/python3.9/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "/mnt/e/voicecraft/gradio_app.py", line 109, in load_models
    "audio_tokenizer": AudioTokenizer(signature=encodec_fn)
  File "/mnt/e/voicecraft/data/tokenizer.py", line 110, in __init__
    model = CompressionSolver.model_from_checkpoint(signature)
  File "/home/cognibuild/src/audiocraft/audiocraft/solvers/compression.py", line 288, in model_from_checkpoint
    assert _checkpoint_path is not None, f"Could not resolve compression model checkpoint path: {checkpoint_path}"
AssertionError: Could not resolve compression model checkpoint path: ./pretrained_models/encodec_4cb2048_giga.th

**Comment by jasonppy** [comment]
it seems that the encodec model is not downloaded to `pretrained_models`, could you check if it's true? and if https://github.com/jasonppy/VoiceCraft/blob/master/gradio_app.py#L111 is happening?

**Comment by gjnave** [comment]
> it seems that the encodec model is not downloaded to `pretrained_models`, could you check if it's true? and if https://github.com/jasonppy/VoiceCraft/blob/master/gradio_app.py#L111 is happening?

There was all sorts of issue with my using WSL. After a 3rd wipe and install, i had permission errors on .cache/hugginspace . omg. lol. I finally chmod owned my own user folder ./cogni and then everything worked.

Having issue now with it only making 2 seconds of audio
