### ISSUE TITLE
Request for a requirements.txt

### ISSUE THREAD

**Issue by pkadambi** [jasonppy/VoiceCraft#9]
Ran into several issues with imports failing after following the instructions in the readme. Installation would have been smoother with exact versions of the offending packages.

**Comment by jasonppy** [comment]
Thanks!

Could you post the issues you encountered?

**Comment by pkadambi** [comment]
Sure, here's the main issue, fixed by downgrading to `transformers==4.28.0`
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/prad/anaconda3/envs/voicecraft/lib/python3.9/site-packages/torchmetrics/__init__.py", line 23, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/home/prad/anaconda3/envs/voicecraft/lib/python3.9/site-packages/torchmetrics/functional/__init__.py", line 121, in <module>
    from torchmetrics.functional.text._deprecated import _bleu_score as bleu_score
  File "/home/prad/anaconda3/envs/voicecraft/lib/python3.9/site-packages/torchmetrics/functional/text/__init__.py", line 50, in <module>
    from torchmetrics.functional.text.bert import bert_score
  File "/home/prad/anaconda3/envs/voicecraft/lib/python3.9/site-packages/torchmetrics/functional/text/bert.py", line 40, in <module>
    from transformers import AutoModel, AutoTokenizer
  File "/home/prad/anaconda3/envs/voicecraft/lib/python3.9/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/home/prad/anaconda3/envs/voicecraft/lib/python3.9/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/home/prad/anaconda3/envs/voicecraft/lib/python3.9/site-packages/transformers/utils/__init__.py", line 33, in <module>
    from .generic import (
  File "/home/prad/anaconda3/envs/voicecraft/lib/python3.9/site-packages/transformers/utils/generic.py", line 478, in <module>
    _torch_pytree.register_pytree_node(
AttributeError: module 'torch.utils._pytree' has no attribute 'register_pytree_node'
```


A second was a torchaudio import error, fixed by force reinstalling `torchaudio==2.0.2`

**Comment by jasonppy** [comment]
Thanks! This is very helpful. I updated the repo with new instructions on setup and also a new environment.yml file.

The transformers version is 4.38.2 in my environment and it worked fine.
