### ISSUE TITLE
Gradio Colab Not working

### ISSUE THREAD

**Issue by Nick088Official** [jasonppy/VoiceCraft#93]
Hey i clicked the Gradio Colab that is like at the start of the repo, i runned all the steps, restarted session, ofc being using the T4 daily free gpu of colab, but when i run the code to run the gradio ui, i get the following error:

`Traceback (most recent call last):
  File "/content/VoiceCraft/gradio_app.py", line 9, in <module>
    from models import voicecraft
  File "/content/VoiceCraft/models/voicecraft.py", line 90, in <module>
    class VoiceCraft(
TypeError: VoiceCraft.__init_subclass__() takes no keyword arguments`

**Comment by jasonppy** [comment]
What's the your huggingface_hub version (0.22.2 works for me)?
```bash
python -c "import huggingface_hub; print(huggingface_hub.__version__)"
```

**Comment by andykaufseo** [comment]
for some reason, the colab installs huggingface-hub-0.20.3.

after updating to 0.22.2 it works fine...

**Comment by pgosar** [comment]
@Sewlell Looks like adding an extra line to update the version would be nice on the Colab

**Comment by jasonppy** [comment]
I just did that https://github.com/jasonppy/VoiceCraft/commit/ddfef8333147c3c988f439bf3a24394d8e189113
